name: "Download data and run model"
on:
  schedule:
    - cron: "0 15 * * *"

jobs:
  build:
    name: Download data, run model and plot results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python3 -m pytest tests/
      - name: Run model
        run: |
          python3 -m src.run
          python3 -m src.details
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
