name: "Download data and run model"
on:
  schedule:
    - cron: "0 17 * * *"

jobs:
  build:
    name: Download data, run model and plot results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python3 -m pytest tests/
      - name: Run model
        run: |
          python3 -m src.run
      - name: Commit files
        run: |
          git config --local user.email "maxscheijen@gmail.com"
          git config --local user.name "Max Scheijen"
          git add .
          git commit -m "Update data and model"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          continue-on-error: true
